# Generated by Django 4.0.6 on 2022-08-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('image', models.ImageField(upload_to=None)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.artist')),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter an arts genre (e.g. painting)', max_length=200),
        ),
        migrations.DeleteModel(
            name='Arts',
        ),
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this artwork', to='gallery.genre'),
        ),
    ]
