# Generated by Django 4.0.6 on 2022-09-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artwork_alter_genre_name_delete_arts_artwork_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='isbn',
        ),
    ]
