# Generated by Django 4.0.6 on 2022-09-11 17:46

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_artist_first_name_alter_artist_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the artwork', max_length=1000),
        ),
    ]
